configuration: Release

nuget: 
 account_feed: true
 project_feed: true
before_build:
 - nuget restore
build:
 verbosity: minimal
- msbuild MvcRepositoryVS2013Demo\MvcRepositoryVS2013Demo\MvcRepositoryVS2013Demo.csproj /t:Package /p:Configuration=Prod;PackageLocation="..\..\MvcRepositoryVS2013Demo.zip"
